Fix a compiler warning
Error: COMPILER_WARNING (CWE-563): [#def1]
kaccounts-integration-25.04.0/src/kcm/accounts.cpp: scope_hint: In constructor ‘AccountsSettings::AccountsSettings(QObject*, const KPluginMetaData&, const QVariantList&)’
kaccounts-integration-25.04.0/src/kcm/accounts.cpp:14:102: warning[-Wunused-parameter]: unused parameter ‘args’

Resolves: https://openscanhub.fedoraproject.org/task/52085/log/kaccounts-integration-25.04.0-1.fc43/scan-results.html#def1

Signed-off-by: Siteshwar Vashisht <svashisht@redhat.com>